import type { Event, Channel, Task, User, Activity, Expense } from '@/types'

export const mockUsers: User[] = [
  {
    id: 'user_1',
    name: 'Ava Patel',
    email: 'ava.patel@eventmgr.io',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ava',
    role: 'owner',
  },
  {
    id: 'user_2',
    name: 'Marcus Chen',
    email: 'marcus.chen@eventmgr.io',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    role: 'organizer',
  },
  {
    id: 'user_3',
    name: 'Sofia Rodriguez',
    email: 'sofia.r@eventmgr.io',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia',
    role: 'team-lead',
  },
  {
    id: 'user_4',
    name: 'James Wilson',
    email: 'james.w@eventmgr.io',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    role: 'member',
  },
  {
    id: 'user_5',
    name: 'Emma Taylor',
    email: 'emma.t@eventmgr.io',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    role: 'member',
  },
]

export const mockEvents: Event[] = [
  {
    id: 'evt_1',
    name: 'Tech Summit 2025',
    type: 'conference',
    date: '2025-12-15',
    venue: 'Convention Center Hall A',
    description: 'Annual technology conference bringing together industry leaders and innovators.',
    status: 'active',
    progress: 65,
    budget: {
      total: 50000,
      spent: 32500,
    },
    teamMembers: ['user_1', 'user_2', 'user_3', 'user_4'],
    channels: ['ch_1', 'ch_2', 'ch_3', 'ch_4'],
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
  },
  {
    id: 'evt_2',
    name: 'Product Launch Gala',
    type: 'social',
    date: '2025-11-20',
    venue: 'Grand Ballroom',
    description: 'Exclusive product launch event with networking and entertainment.',
    status: 'planning',
    progress: 35,
    budget: {
      total: 35000,
      spent: 8750,
    },
    teamMembers: ['user_1', 'user_3', 'user_5'],
    channels: ['ch_5', 'ch_6', 'ch_7'],
    createdAt: '2024-10-15T00:00:00Z',
    updatedAt: '2024-11-10T00:00:00Z',
  },
  {
    id: 'evt_3',
    name: 'Leadership Workshop',
    type: 'workshop',
    date: '2025-10-05',
    venue: 'Training Center',
    description: 'Interactive workshop on modern leadership strategies.',
    status: 'completed',
    progress: 100,
    budget: {
      total: 15000,
      spent: 14200,
    },
    teamMembers: ['user_2', 'user_4'],
    channels: ['ch_8'],
    createdAt: '2024-08-01T00:00:00Z',
    updatedAt: '2024-10-06T00:00:00Z',
  },
]

export const mockChannels: Channel[] = [
  {
    id: 'ch_1',
    eventId: 'evt_1',
    name: 'Decoration',
    description: 'Venue decoration and setup',
    icon: '🎨',
    color: 'bg-gradient-to-br from-[#E8D5F2] to-[#D5C6F2]',
    budget: {
      allocated: 12000,
      spent: 8500,
    },
    taskCount: 12,
    completedTasks: 8,
    memberCount: 3,
    lastActivity: '2 hours ago',
  },
  {
    id: 'ch_2',
    eventId: 'evt_1',
    name: 'Logistics',
    description: 'Transportation and equipment',
    icon: '🚚',
    color: 'bg-gradient-to-br from-[#FFD7BA] to-[#FEC5BB]',
    budget: {
      allocated: 15000,
      spent: 10200,
    },
    taskCount: 15,
    completedTasks: 10,
    memberCount: 4,
    lastActivity: '1 hour ago',
  },
  {
    id: 'ch_3',
    eventId: 'evt_1',
    name: 'Marketing',
    description: 'Promotion and publicity',
    icon: '📢',
    color: 'bg-gradient-to-br from-[#D5F2E3] to-[#B8E6D5]',
    budget: {
      allocated: 18000,
      spent: 12800,
    },
    taskCount: 20,
    completedTasks: 13,
    memberCount: 5,
    lastActivity: '30 minutes ago',
  },
  {
    id: 'ch_4',
    eventId: 'evt_1',
    name: 'Catering',
    description: 'Food and beverages',
    icon: '🍽️',
    color: 'bg-gradient-to-br from-[#FFF4D5] to-[#FFE8B8]',
    budget: {
      allocated: 5000,
      spent: 1000,
    },
    taskCount: 8,
    completedTasks: 1,
    memberCount: 2,
    lastActivity: '5 hours ago',
  },
]

export const mockTasks: Task[] = [
  {
    id: 'task_1',
    eventId: 'evt_1',
    channelId: 'ch_1',
    title: 'Design stage backdrop',
    description: 'Create and install main stage backdrop with brand colors',
    assignee: 'user_3',
    dueDate: '2025-11-25',
    priority: 'high',
    status: 'in-progress',
    progress: 60,
    subtasks: [
      { id: 'st_1', title: 'Create design mockup', completed: true },
      { id: 'st_2', title: 'Get approval', completed: true },
      { id: 'st_3', title: 'Order materials', completed: false },
      { id: 'st_4', title: 'Install', completed: false },
    ],
    comments: [],
    attachments: [],
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2024-11-15T00:00:00Z',
  },
  {
    id: 'task_2',
    eventId: 'evt_1',
    channelId: 'ch_2',
    title: 'Book transportation',
    description: 'Arrange shuttle buses for attendees',
    assignee: 'user_4',
    dueDate: '2025-11-18',
    priority: 'high',
    status: 'todo',
    progress: 0,
    subtasks: [],
    comments: [],
    attachments: [],
    createdAt: '2024-11-05T00:00:00Z',
    updatedAt: '2024-11-05T00:00:00Z',
  },
  {
    id: 'task_3',
    eventId: 'evt_1',
    channelId: 'ch_3',
    title: 'Social media campaign',
    description: 'Launch promotional campaign across all platforms',
    assignee: 'user_2',
    dueDate: '2025-11-10',
    priority: 'medium',
    status: 'done',
    progress: 100,
    subtasks: [
      { id: 'st_5', title: 'Create content calendar', completed: true },
      { id: 'st_6', title: 'Design graphics', completed: true },
      { id: 'st_7', title: 'Schedule posts', completed: true },
    ],
    comments: [],
    attachments: [],
    createdAt: '2024-10-20T00:00:00Z',
    updatedAt: '2024-11-10T00:00:00Z',
  },
  {
    id: 'task_4',
    eventId: 'evt_1',
    channelId: 'ch_3',
    title: 'Email newsletter',
    description: 'Send event details to subscriber list',
    assignee: 'user_2',
    dueDate: '2025-11-22',
    priority: 'medium',
    status: 'review',
    progress: 80,
    subtasks: [],
    comments: [],
    attachments: [],
    createdAt: '2024-11-08T00:00:00Z',
    updatedAt: '2024-11-14T00:00:00Z',
  },
  {
    id: 'task_5',
    eventId: 'evt_1',
    channelId: 'ch_4',
    title: 'Finalize menu',
    description: 'Choose catering menu with vendor',
    assignee: 'user_5',
    dueDate: '2025-11-20',
    priority: 'low',
    status: 'in-progress',
    progress: 40,
    subtasks: [],
    comments: [],
    attachments: [],
    createdAt: '2024-11-12T00:00:00Z',
    updatedAt: '2024-11-13T00:00:00Z',
  },
]

export const mockActivities: Activity[] = [
  {
    id: 'act_1',
    eventId: 'evt_1',
    userId: 'user_2',
    type: 'task_completed',
    description: 'completed "Social media campaign"',
    metadata: { taskId: 'task_3' },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_2',
    eventId: 'evt_1',
    userId: 'user_3',
    type: 'task_created',
    description: 'created task "Design stage backdrop"',
    metadata: { taskId: 'task_1' },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_3',
    eventId: 'evt_1',
    userId: 'user_1',
    type: 'expense_added',
    description: 'added expense for venue deposit',
    metadata: { amount: 10000 },
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_4',
    eventId: 'evt_1',
    userId: 'user_1',
    type: 'member_added',
    description: 'invited Emma Taylor to the team',
    metadata: { userId: 'user_5' },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockExpenses: Expense[] = [
  {
    id: 'exp_1',
    eventId: 'evt_1',
    channelId: 'ch_1',
    amount: 5000,
    category: 'Materials',
    description: 'Stage backdrop materials',
    vendor: 'Event Supplies Co',
    date: '2024-11-10',
    status: 'approved',
    receipt: null,
    approvedBy: 'user_1',
    createdAt: '2024-11-10T00:00:00Z',
  },
  {
    id: 'exp_2',
    eventId: 'evt_1',
    channelId: 'ch_2',
    amount: 8000,
    category: 'Transportation',
    description: 'Shuttle bus rental',
    vendor: 'Transport Services Inc',
    date: '2024-11-12',
    status: 'pending',
    receipt: null,
    approvedBy: null,
    createdAt: '2024-11-12T00:00:00Z',
  },
  {
    id: 'exp_3',
    eventId: 'evt_1',
    channelId: 'ch_3',
    amount: 3500,
    category: 'Marketing',
    description: 'Social media ad campaign',
    vendor: 'Digital Marketing Agency',
    date: '2024-11-05',
    status: 'approved',
    receipt: null,
    approvedBy: 'user_1',
    createdAt: '2024-11-05T00:00:00Z',
  },
]
